package de.test.quarkus;

import io.quarkus.runtime.annotations.RegisterForReflection;

/**
 * this is a helper class to mark external classes for reflection instead of using reflection-config.json, classes must be comma-separated
 */
@RegisterForReflection(targets = {
        net.sf.jasperreports.engine.base.JRBaseDatasetParameter.class,
        net.sf.jasperreports.engine.base.JRBaseDatasetParameter[].class,
        net.sf.jasperreports.engine.base.JRBaseReport.class,
        net.sf.jasperreports.engine.util.JRLoader.class,
        net.sf.jasperreports.engine.util.ContextClassLoaderObjectInputStream.class,
        net.sf.jasperreports.functions.standard.ReportFunctions.class,
        net.sf.jasperreports.functions.standard.MathFunctions.class,
        net.sf.jasperreports.functions.standard.LogicalFunctions.class,
        net.sf.jasperreports.functions.standard.TextFunctions.class,
        net.sf.jasperreports.functions.standard.DateTimeFunctions.class,
        net.sf.jasperreports.repo.SerializedObjectPersistenceService.class,
        java.awt.Toolkit.class,
        net.sf.jasperreports.engine.JasperCompileManager.class,
        net.sf.jasperreports.engine.JasperFillManager.class,
        net.sf.jasperreports.components.table.fill.TableReportScriptlet.class,
        // from https://stackoverflow.com/questions/76219135/error-with-quarkus-native-and-jasperreport
      //  net.sf.jasperreports.engine.xml.JRReportSaxParserFactory.class,
      //  net.sf.jasperreports.engine.export.XmpWriter.class,
        com.lowagie.text.pdf.crypto.AESCipher.class,
        com.lowagie.text.pdf.PdfPublicKeySecurityHandler.class,
      //  net.sf.jas.eng.exp.PdfXmpCreator.class,
        net.sf.jasperreports.renderers.AbstractSvgDataToGraphics2DRenderer.class,
      //  net.sf.jasperreports.web.util.AbstractWebResourceHandler.class,
        net.sf.jasperreports.renderers.util.SvgFontProcessor.class,
     //   net.sf.jasperreports.engine.xml.JRXmlDigester.class,
     //   net.sf.jasperreports.engine.xml.JasperDesignFactory.class,
     //   net.sf.jasperreports.engine.xml.JRQueryFactory.class,
        net.sf.jasperreports.engine.design.JRDesignQuery.class,
        net.sf.jasperreports.engine.design.JasperDesign.class,
       // com.sun.org.apache.xerces.internal.impl.dv.xs.SchemaDVFactoryImpl.class,
       // net.sf.jasperreports.engine.xml.JRBandFactory.class,
      //  net.sf.jasperreports.components.headertoolbar.HeaderToolbarParameterContributorExtensionFactory.class,
        net.sf.jasperreports.types.date.DateRangeQueryClauseExtensions.class,
        net.sf.jasperreports.repo.DefaultRepositoryExtensionsRegistryFactory.class,
        net.sf.jasperreports.parts.PartComponentsExtensionsRegistryFactory.class,
        net.sf.jasperreports.web.util.ContentTypeMappingExtensionsRegistryFactory.class,
        net.sf.jasperreports.engine.fonts.SimpleFontExtensionsRegistryFactory.class,
       // net.sf.jasperreports.data.DefaultDataAdapterServiceExtensionsRegistryFactory.class,
      //  net.sf.jasperreports.web.util.WebResourceHandlersExtensionRegistryFactory.class,
      //  net.sf.jasperreports.util.CastorMappingExtensionsRegistryFactory.class,
        net.sf.jasperreports.engine.export.MatcherExportFilterMappingExtensionsRegistryFactory.class,
        net.sf.jasperreports.governors.GovernorExtensionsRegistryFactory.class,
       // net.sf.jasperreports.web.util.RequirejsModuleMappingExtensionsRegistryFactory.class,
        net.sf.jasperreports.engine.query.SQLQueryClauseFunctionsExtensions.class,
        net.sf.jasperreports.engine.style.PropertyStyleProviderExtensionFactory.class,
      //  net.sf.jasperreports.web.util.JacksonMappingExtensionsRegistryFactory.class,
        net.sf.jasperreports.extensions.DefaultExtensionsRegistryFactory.class,
        net.sf.jasperreports.components.ComponentsExtensionsRegistryFactory.class,
      //  net.sf.jasperreports.components.headertoolbar.HeaderToolbarConditionalStyleProviderExtensionFactory.class,
      //  com.sun.org.apache.xerces.internal.util.XMLGrammarPoolImpl.class,
        net.sf.jasperreports.engine.query.JRJdbcQueryExecuterFactory.class,
        net.sf.jasperreports.engine.util.ResourceBundleMessageProviderFactory.class,
        net.sf.jasperreports.engine.JRBand.class,
        net.sf.jasperreports.engine.design.JRDesignSection.class,
      //  net.sf.jasperreports.engine.xml.JRSectionFactory$DetailSectionFactory.class,
        net.sf.jasperreports.engine.xml.JRXmlLoader.class,
      //  net.sf.jasperreports.data.DataAdapterParameterContributorExtensionsRegistryFactory.class,
        net.sf.jasperreports.engine.design.JRJavacCompiler.class,
       // net.sf.jasperreports.util.JacksonMappingExtensionsRegistryFactory.class,
      //  net.sf.jasperreports.export.pdf.classic.ClassicPdfProducer.class,
      //  net.sf.jasperreports.export.pdf.classic.ClassicPdfProducerFactory.class,
      //  net.sf.jasperreports.export.pdf.classic.GlyphRendering.class,
        com.lowagie.text.pdf.PdfName.class,
      //  net.sf.jasperreports.export.type.PdfVersionEnum.class,
      //  net.sf.jasperreports.export.type.PdfPrintScalingEnum.class,
      //  net.sf.jasperreports.export.type.PdfaConformanceEnum.class,
        net.sf.jasperreports.engine.export.DefaultExporterFilterFactory.class,
        net.sf.jasperreports.engine.export.ElementPropertyExporterFilterFactory.class,
        net.sf.jasperreports.engine.export.JROriginExporterFilterFactory.class,
        net.sf.jasperreports.engine.export.MatcherExporterFilterFactory.class,
        net.sf.jasperreports.engine.export.ElementKeyExporterFilterFactory.class,
        com.lowagie.text.pdf.BaseFont.class

}, registerFullHierarchy = true)
public class ReflectionCallInitializer {

}
